name: Frontend Image

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    env:
      FRONTEND_DEPLOY_HOOK: ${{ secrets.FRONTEND_DEPLOY_HOOK }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Set Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: front

      - name: Build frontend
        run: npm run build
        working-directory: front

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest

      - name: Trigger release
        if: ${{ env.FRONTEND_DEPLOY_HOOK }}
        run: curl ${{ env.FRONTEND_DEPLOY_HOOK }}
